# Generated by Django 5.0.7 on 2024-07-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
    ]
